@ruta = http://localhost:5064/api/User

### List User
GET {{ruta}}/Select
Content-Type: application/json

### Register User
POST {{ruta}}/Register
Content-Type: application/json

{
  "name": "Pedro",
  "lastName": "catulo",
  "email": "pedro@gmail.com",
  "password": "index"
}
### Delete User
DELETE {{ruta}}/Remove/22
Content-Type: application/json

### Edit User

PUT {{ruta}}/Edit/25
Content-Type: application/json

{
  "name": "Rodolfo",
  "lastName": "Astro",
  "email": "rodolfo@gmailcom",
  "password": "index"
}